Resources:
  EventTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        -
          AttributeName: userId
          AttributeType: S
        -
          AttributeName: eventId
          AttributeType: S
      KeySchema:
        -
          AttributeName: eventId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: ${self:service}-${opt:stage, self:provider.stage}-EVENT_TABLE
      GlobalSecondaryIndexes:
        - IndexName: UserId
          KeySchema:
          - AttributeName: userId
            KeyType: HASH
          Projection:
            NonKeyAttributes:
            - eventTitle
            - eventDate
            ProjectionType: INCLUDE
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
